### ISSUE TITLE
compute.py 7월 4주차 인증 체크 관련 이슈

### ISSUE THREAD

**Issue by malgamlee** [SystemOutGirlsAlgorithm/algorithm#108]
구현해주신 compute.py 프로그램이 자동으로 잘 작동하여 7월 리드미 반영이 완료 되었습니다 !

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/88325253/182035555-6345f1bd-ae88-45b2-829f-6b9c6dc7fe5d.png">

(좌 : algo bot update, 우 : 말감 update)
그런데 확인해보니 위와 같이 살짝 이슈가 발생한 것을 확인했습니다.

1. 4주차가 아닌 5주차로 작성됨
2. 2022-07-25로 작동된 것이 아니라 2022-07-31로 작동된 것으로 보임

제가 확인한 이슈는 이 두 가지 입니다. 확인 부탁드립니다!

**Comment by mimseong** [comment]
오 이슈 감사합니다! 한번 확인해볼게요

**Comment by mimseong** [comment]
@malgamlee @heyoni 

스크립트 돌릴 때 시간을 따로 받지 않고 현재 시간 기준으로 저번주 월요일부터 계산하도록 수정했습니다!
EX) 8월 6일 토요일날에 스크립트를 돌릴 경우 -> 8월 1일 월요일 부터 계산하도록 변경
